export default {
    variants: [
        'red',
        'blue',
        'yellow',
        'green',
        'orange',
        'purple',
        'white',
        'black',
        'skyblue',
        'macncheese',
        'lilac',
        'cyan',
        'jazzberry',
        'heatherblue',
    ],
    red: '#DB3127',
    blue: '#3580C2',
    yellow: '#f2de48',
    green: '#43a447',
    white: '#ffffff',
    black: '#000000',
    orange: '#EC6E60',
    purple: '#663399',

    skyblue: '#87CEEB',
    macncheese: '#ffbd88',
    lilac: '#C8A2C8',
    cyan: '#0EB8BE',
    jazzberry: '#a50b5e',
    heatherblue: '#6B83A4'
}