export default {
    variants: [
        'red',
        'blue',
        'yellow',
        'green',
        'orange',
        'purple',
        'white',
        'black',
    ],
    red: '#DB3127',
    blue: '#3580C2',
    yellow: '#f2de48',
    green: '#43a447',
    white: '#ffffff',
    black: '#000000',
    orange: '#ff8800',
    purple: '#702cd6',
}